# SPDX-License-Identifier: GPL-3.0-or-later
"""Type stubs for the compiled ``am1_rs._native`` extension.

The extension returns plain dicts rather than typed objects, so the return annotations here are
``dict[str, Any]``; the keys of each are documented on the corresponding wrapper in
:mod:`am1_rs.native`, which is the surface users should call.
"""

from typing import Any, Sequence

def single_point(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def gradient(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def orbitals(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def molden(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> str: ...
def ir_spectrum(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def dipole_derivatives(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def orbital_response(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
    response_density: bool = ...,
) -> dict[str, Any]: ...
def vibrations(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
    hessian: bool = ...,
    frequencies: bool = ...,
    ir: bool = ...,
    orbital_response: bool = ...,
    response_density: bool = ...,
) -> dict[str, Any]: ...
def pbc_hessian(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...
def born_charges(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...
def polarizability(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...def dielectric_function(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    q: Sequence[float],
    chain_radius: float | None = ...,
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> float: ...def polarization(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    strings: int = ...,
    charge: float = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...
def finite_field(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    field: Sequence[float],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
    outer_mixing: float = ...,
) -> dict[str, Any]: ...def dielectric(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...
def dielectric_with_extent(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    slab_thickness: float | None = ...,
    wire_cross_section: float | None = ...,
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
) -> dict[str, Any]: ...
def dfpt(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    q_points: Sequence[Sequence[float]],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    long_range: str = ...,
    cpscf_tol: float = ...,
    cpscf_max_iter: int = ...,
    cpscf_mixing: float = ...,
) -> dict[str, Any]: ...
def lo_to_frequencies(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    supercell: tuple[int, int, int] = ...,
    direction: tuple[float, float, float] = ...,
    q_points: Sequence[Sequence[float]] | None = ...,
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    enforce_acoustic_sum_rule: bool = ...,
) -> dict[str, Any]: ...
def phonons(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    supercell: tuple[int, int, int],
    q_points: Sequence[Sequence[float]] | None = ...,
    charge: float = ...,
    multiplicity: int = ...,
    method: str = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    enforce_acoustic_sum_rule: bool = ...,
) -> dict[str, Any]: ...
def constants() -> dict[str, float]: ...
def pbc_point(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    cell: Sequence[Sequence[float]],
    pbc: Sequence[bool],
    kpts: tuple[int, int, int] = ...,
    charge: float = ...,
    multiplicity: int = ...,
    unrestricted: bool = ...,
    smearing_ev: float = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
    method: str = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    mixing: float = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def divide_conquer(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    core_size: int = ...,
    buffer_radius: float = ...,
    smearing_ev: float = ...,
    e_tol: float = ...,
    p_tol: float = ...,
    max_scf: int = ...,
    mixing: float = ...,
    gap_warn_ev: float = ...,
    forces: bool = ...,
    multipole_cutoff: float | None = ...,
    electric_field: Sequence[float] | None = ...,
    cell: Sequence[Sequence[float]] | None = ...,
    pbc: Sequence[bool] | None = ...,
    realspace_cutoff: float = ...,
    exchange_cutoff: float = ...,
) -> dict[str, Any]: ...
def optimize(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def hessian(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def frequencies(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
    reference: str = ...,
    method: str = ...,
    electric_field: Sequence[float] | None = ...,
) -> dict[str, Any]: ...
def am1_bcc(
    numbers: Sequence[int],
    positions: Sequence[Sequence[float]],
    charge: float = ...,
    multiplicity: int = ...,
) -> dict[str, Any]: ...
